language: scala
scala:
   - 2.11.6
script: sbt compile

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ba2f3507b55e178747d5
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false